@startuml
title MessageReaction.MessageReaction

actor Caller
participant MessageReaction

Caller -> MessageReaction: new(currentcategories)
MessageReaction -> MessageReaction: set currentcategories
@enduml
